/*
First, city_low_poly_compressed.glb file was compressed with the following:
  gltf-transform resize city_low_poly.glb city_low_poly_compressed.glb --width 1024 --height 1024
  (3.98 MB) → (3.66 MB)

  gltf-transform webp city_low_poly_compressed.glb city_low_poly_compressed.glb
  (3.66 MB) → (1.04 MB)

  gltf-transform draco city_low_poly_compressed.glb city_low_poly_compressed.glb
  (1.04 MB) → (258.07 KB)

  Note: The draco compression made the crosswalk details look bad, so I redid the
  compression sequence and stopped before the draco step.
---- 
Then, JSX was auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 city_low_poly_compressed.glb --types
----

Afterwards I've edited this to reduce the blur on faraway parts of the road.
*/

import * as THREE from 'three'
import React, { useCallback, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useThree } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Plane429: THREE.Mesh
    Plane429_1: THREE.Mesh
    Plane429_2: THREE.Mesh
    Plane429_3: THREE.Mesh
    Plane429_4: THREE.Mesh
    Plane429_5: THREE.Mesh
    Plane312: THREE.Mesh
    Plane312_1: THREE.Mesh
    Plane312_2: THREE.Mesh
    Plane312_3: THREE.Mesh
    Plane312_4: THREE.Mesh
    Plane312_5: THREE.Mesh
  }
  materials: {
    roof: THREE.MeshStandardMaterial
    two_window_concrete: THREE.MeshStandardMaterial
    brick_panel: THREE.MeshStandardMaterial
    two_window_dark: THREE.MeshStandardMaterial
    two_window_black: THREE.MeshStandardMaterial
    glass_panel: THREE.MeshStandardMaterial
    sidewalk_efficient: THREE.MeshStandardMaterial
    sidewalk_corner: THREE.MeshStandardMaterial
    sidewalk_corner_bumps: THREE.MeshStandardMaterial
    road: THREE.MeshStandardMaterial
    pavement: THREE.MeshStandardMaterial
    road_crosswalk: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function CityModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/city_low_poly_compressed.glb') as GLTFResult
  const { gl } = useThree();

  const reduceRoadBlur = useCallback(() => {
    const texturesToSharpen = [
      materials.road.map,
      materials.road_crosswalk.map,
    ];
    texturesToSharpen.forEach(texture => {
      if (texture) {
        texture.anisotropy = gl.capabilities.getMaxAnisotropy();
      }
    });
  }, [materials]);

  useEffect(() => {
    reduceRoadBlur();
  }, []);

  return (
    <group {...props} dispose={null}>
      <group position={[209.238, 80, -18]}>
        <mesh geometry={nodes.Plane429.geometry} material={materials.roof} />
        <mesh geometry={nodes.Plane429_1.geometry} material={materials.two_window_concrete} />
        <mesh geometry={nodes.Plane429_2.geometry} material={materials.brick_panel} />
        <mesh geometry={nodes.Plane429_3.geometry} material={materials.two_window_dark} />
        <mesh geometry={nodes.Plane429_4.geometry} material={materials.two_window_black} />
        <mesh geometry={nodes.Plane429_5.geometry} material={materials.glass_panel} />
      </group>
      <group position={[-132, 0, -1]}>
        <mesh geometry={nodes.Plane312.geometry} material={materials.sidewalk_efficient} />
        <mesh geometry={nodes.Plane312_1.geometry} material={materials.sidewalk_corner} />
        <mesh geometry={nodes.Plane312_2.geometry} material={materials.sidewalk_corner_bumps} />
        <mesh geometry={nodes.Plane312_3.geometry} material={materials.road} />
        <mesh geometry={nodes.Plane312_4.geometry} material={materials.pavement} />
        <mesh geometry={nodes.Plane312_5.geometry} material={materials.road_crosswalk} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/city_low_poly_compressed.glb')
