/*
First, city_tile_compressed.glb file was compressed with the following:
  gltf-transform resize city_tile.glb city_tile_compressed.glb --width 1024 --height 1024
  (3.29 MB) → (2.97 MB)

  gltf-transform webp city_tile_compressed.glb city_tile_compressed.glb
  (2.97 MB) → (346.07 KB)

  gltf-transform draco city_tile_compressed.glb city_tile_compressed.glb

  Note: The draco compression made the crosswalk details look bad, so I redid the
  compression sequence and stopped before the draco step.
---- 
Then, JSX was auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 city_tile_compressed.glb --types
----

Afterwards I've edited this to reduce the blur on faraway parts of the road.
*/

import * as THREE from 'three'
import React, { useCallback, useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useThree } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Plane289: THREE.Mesh
    Plane289_1: THREE.Mesh
    Plane289_2: THREE.Mesh
    Plane289_3: THREE.Mesh
    Plane289_4: THREE.Mesh
    Plane289_5: THREE.Mesh
    Plane290: THREE.Mesh
    Plane290_1: THREE.Mesh
    Plane290_2: THREE.Mesh
    Plane290_3: THREE.Mesh
    Plane290_4: THREE.Mesh
    Plane290_5: THREE.Mesh
  }
  materials: {
    roof: THREE.MeshStandardMaterial
    two_window_concrete: THREE.MeshStandardMaterial
    brick_panel: THREE.MeshStandardMaterial
    two_window_dark: THREE.MeshStandardMaterial
    two_window_black: THREE.MeshStandardMaterial
    glass_panel: THREE.MeshStandardMaterial
    sidewalk_efficient: THREE.MeshStandardMaterial
    sidewalk_corner: THREE.MeshStandardMaterial
    sidewalk_corner_bumps: THREE.MeshStandardMaterial
    road: THREE.MeshStandardMaterial
    pavement: THREE.MeshStandardMaterial
    road_crosswalk: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function CityTileModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/city_tile_compressed.glb') as GLTFResult;
  const { gl } = useThree();
  
  const reduceRoadBlur = useCallback(() => {
    const texturesToSharpen = [
      materials.road.map,
      materials.road_crosswalk.map,
    ];
    texturesToSharpen.forEach(texture => {
      if (texture) {
        texture.anisotropy = gl.capabilities.getMaxAnisotropy();
      }
    });
  }, [materials, gl.capabilities]);

  useEffect(() => {
    reduceRoadBlur();
  }, [reduceRoadBlur]);

  return (
    <group {...props} dispose={null}>
      <group position={[209.238, 80, -18]}>
        <mesh geometry={nodes.Plane289.geometry} material={materials.roof} />
        <mesh geometry={nodes.Plane289_1.geometry} material={materials.two_window_concrete} />
        <mesh geometry={nodes.Plane289_2.geometry} material={materials.brick_panel} />
        <mesh geometry={nodes.Plane289_3.geometry} material={materials.two_window_dark} />
        <mesh geometry={nodes.Plane289_4.geometry} material={materials.two_window_black} />
        <mesh geometry={nodes.Plane289_5.geometry} material={materials.glass_panel} />
      </group>
      <group position={[-132, 0, -1]}>
        <mesh geometry={nodes.Plane290.geometry} material={materials.sidewalk_efficient} />
        <mesh geometry={nodes.Plane290_1.geometry} material={materials.sidewalk_corner} />
        <mesh geometry={nodes.Plane290_2.geometry} material={materials.sidewalk_corner_bumps} />
        <mesh geometry={nodes.Plane290_3.geometry} material={materials.road} />
        <mesh geometry={nodes.Plane290_4.geometry} material={materials.pavement} />
        <mesh geometry={nodes.Plane290_5.geometry} material={materials.road_crosswalk} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/city_tile_compressed.glb');
